### ISSUE TITLE
Nethserver problems with registration.

### ISSUE THREAD

**Issue by Hx0S** [nethesis/icaro#147]
`Error retrieving hotspot list.`
That's all error message that I got. using dedalo from cli I got this:
`Error: unit not added!`
There is no any description of error.

**Comment by gsanchietti** [comment]
That's probably because the client can't contact the server.

Did you see this howto https://community.nethserver.org/t/install-dedalo-hotspot-with-icaro-on-local-servers/15247?

**Comment by Hx0S** [comment]
Thank you for answer. I did installation by this manual. neth and Icaro can ping each other. I can connect to Icaro via browser, nmap(on nethserver) shows that all needed ports are open, and I can bring authorization key from nethserver machine. client able to contact the server.

**Comment by gsanchietti** [comment]
Sorry but I'm not an expert.
Do you mind opening a new topic inside https://community.nethserver.org?

I guess other people can help better than me.

**Comment by gsanchietti** [comment]
I'm closing this one, fell free to reach on the linked forum.
