### ISSUE TITLE
Hotspot manager. Visualize current units states

### ISSUE THREAD

**Issue by tonyco97** [nethesis/icaro#149]
Possibility to see if a unit is active or not in the unit summary page.

**Proposed solution**

Continuous check if a unit has active sessions in the previous 30 minutes:
- if so, the active status will appear with a green symbol
- if not, the inactive status will appear with a red symbol

**Comment by cotosso** [comment]
It works as expected, now every unit shows if there are active sessions.

**Comment by edospadoni** [comment]
released with `v70` (https://github.com/nethesis/icaro/releases/tag/v70)
