### ISSUE TITLE
Customize Chilli DHCP Leases (default 512)

### ISSUE THREAD

**Issue by cotosso** [nethesis/icaro#158]
I had some problem in very large environments because the chilli DHCP refuse to dish out more than 512 leases, we can see in the logs this message:

```
reached max connections 512!
```

So I found that the dhcp of chilli by default manages until 512 IP addresses, but luckily this value can be customized via the variable maxclients.
I would like to have this variable implemented in the hotspot so that it can handle these cases easily.

For testing see: https://github.com/NethServer/dev/issues/6634

**Comment by edospadoni** [comment]
Verified by: https://github.com/NethServer/dev/issues/6634

**Comment by edospadoni** [comment]
dedalo released in `7.9.2009/updates`
