### ISSUE TITLE
Use Hotspot Id instead of Hotspot name in unit registration

### ISSUE THREAD

**Issue by edospadoni** [nethesis/icaro#67]
At the moment when a new unit is added using the `dedalo` helper, the reference to the hotspot is only the name, that could be not unique and the result is that the unit is not correctly added to the right hotspot.

Steps
1. Create a hotspot  and name it `test` with some description
2. Create another hotspot and name it again `test` with some description
3. Try to register an unit using the hotspot named `test`.
4. The registration fails because the unit is added to a bad hotspot

We must change the registration method by modify the `sun-api` endpoint `POST /units` to accept `hotspot_id` filed in JSON request instead of `hotspot` (that contains the name)

**Comment by gsanchietti** [comment]
Packages released for NS 7:
- nethserver-dedalo-1.0.2-1.ns7.noarch.rpm
- dedalo-0.2.0-1.ns7.noarch.rpm
