### ISSUE TITLE
Web Proxy bypasses not working for hotspot traffic

### ISSUE THREAD

**Issue by cotosso** [nethesis/icaro#99]
Hotspot with proxy enabled.
Proxy bypasses defined in the web proxy panel are not working for hotspot traffic.

**Steps to reproduce**

- Enable hotspot with the proxy flag
- Enable web proxy
- Define one or more bypasses in the web proxy page : by source, destination or domain (in this case hotspot clients should use hotspot interface ip address as dns)

**Expected behavior**

Defined exception are not intercepted by proxy

**Actual behavior**

Defined exception are still intercepted by proxy

**Components**

NethServer release 7.6.1810 (final)

nethserver-squid-1.7.4-1.ns7.noarch
squid-3.5.20-999.ns7.x86_64
nethserver-dedalo-1.0.7-1.ns7.noarch
dedalo-0.2.1-1.ns7.noarch

**Comment by cotosso** [comment]
Proxy bypasses are realized at firewall level, the proxy redirect rule for hotspot lacks exceptions that are present for local networks.
I suggest implementing the same exceptions management already present in the firewall for local networks.

**Comment by gsanchietti** [comment]
Wrong issue tracker.

Moved to NethServer/dev#5765
